[package]
name = "actix-macros"
version = "0.2.0-beta.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix runtime macros"
repository = "https://github.com/actix/actix-net"
documentation = "https://docs.rs/actix-macros/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.3"
syn = { version = "^1", features = ["full"] }

[features]
actix-reexport = []

[dev-dependencies]
actix-rt = { git = 'https://github.com/inq/actix-net.git'}

futures-util = { version = "0.3", default-features = false }
trybuild = "1"
